/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { english } from "./english";

// prettier-ignore
export const schinese = {
  ...english,
  ApplyPatchUse: /* csgo_schinese.txt */"应用布章",
  ApplyPatchWarn: /* csgo_schinese.txt */"一个布章只能被应用一次",
  ApplyStickerCancel: /* csgo_schinese.txt */"取消",
  ApplyStickerUse: /* csgo_schinese.txt */"应用印花",
  ApplyStickerUseOn: /* csgo_schinese.txt */"使用",
  ApplyStickerWarn: /* csgo_schinese.txt */"一个印花只能被应用一次",
  CaseAdd: /* csgo_schinese.txt */"添加",
  CaseClose: /* csgo_schinese.txt */"关闭",
  CaseContainsOne: /* csgo_schinese.txt */"包含下列物品之一：",
  CaseNeed: /* csgo_schinese.txt */"这个操作需要一个",
  CaseOnceWarn: /* csgo_schinese.txt */"这个武器箱只能打开一次",
  CaseRareItem: /* csgo_schinese.txt */"★ 罕见的特殊物品 ★",
  CaseUnlock: /* csgo_schinese.txt */"解锁",
  CaseUnlockContainer: /* csgo_schinese.txt */"开箱",
  CaseUse: /* csgo_schinese.txt */"使用",
  CategoryAgent: /* csgo_schinese.txt */"探员",
  CategoryCase: /* csgo_schinese.txt */"武器箱",
  CategoryCollectible: /* csgo_schinese.txt */"收藏品",
  CategoryEquipment: /* csgo_schinese.txt */"装备",
  CategoryGlove: /* csgo_schinese.txt */"手套",
  CategoryGraffiti: /* csgo_schinese.txt */"涂鸦",
  CategoryHeavy: /* csgo_schinese.txt */"重型武器",
  CategoryKey: /* csgo_schinese.txt */"钥匙",
  CategoryKnife: /* csgo_schinese.txt */"匕首",
  CategoryMusicKit: /* csgo_schinese.txt */"音乐盒",
  CategoryPatch: /* csgo_schinese.txt */"布章",
  CategoryPistol: /* csgo_schinese.txt */"手枪",
  CategoryRifle: /* csgo_schinese.txt */"步枪",
  CategorySMG: /* csgo_schinese.txt */"微型冲锋枪",
  CategorySticker: /* csgo_schinese.txt */"印花",
  CategoryTool: /* csgo_schinese.txt */"工具",
  EditorCancel: /* csgo_schinese.txt */"取消",
  EditorNametag: /* csgo_schinese.txt */"名称标签",
  EditorPatches: /* csgo_schinese.txt */"布章",
  EditorQuantity: /* csgo_schinese.txt */"数量",
  EditorRandom: /* csgo_schinese.txt */"随机",
  EditorReset: /* csgo_schinese.txt */"重置",
  EditorSave: /* csgo_schinese.txt */"保存",
  EditorSeed: /* csgo_schinese.txt */"图案",
  EditorStatTrak: /* csgo_schinese.txt */"StatTrak™",
  EditorStickers: /* csgo_schinese.txt */"印花",
  EditorWear: /* csgo_schinese.txt */"磨损程度",
  InspectClose: /* csgo_schinese.txt */"关闭",
  InventoryApplyPatch: /* csgo_schinese.txt */"应用布章",
  InventoryApplySticker: /* csgo_schinese.txt */"应用印花",
  InventoryFilterAgents: /* csgo_schinese.txt */"探员",
  InventoryFilterAll: /* csgo_schinese.txt */"所有",
  InventoryFilterAllEquipment: /* csgo_schinese.txt */"全套装备",
  InventoryFilterAllGraphicArt: /* csgo_schinese.txt */"全部艺术作品",
  InventoryFilterAlphabetical: /* csgo_schinese.txt */"字母排序",
  InventoryFilterCollection: /* csgo_schinese.txt */"收藏品",
  InventoryFilterContainers: /* csgo_schinese.txt */"武器箱",
  InventoryFilterDisplay: /* csgo_schinese.txt */"展示品",
  InventoryFilterEquipment: /* csgo_schinese.txt */"装备",
  InventoryFilterEquipped: /* csgo_schinese.txt */"已装备",
  InventoryFilterEverything: /* csgo_schinese.txt */"全部",
  InventoryFilterGloves: /* csgo_schinese.txt */"手套",
  InventoryFilterGraffiti: /* csgo_schinese.txt */"涂鸦",
  InventoryFilterGraffitiBoxes: /* csgo_schinese.txt */"涂鸦箱",
  InventoryFilterGraphicArt: /* csgo_schinese.txt */"艺术作品",
  InventoryFilterMedals: /* csgo_schinese.txt */"徽章",
  InventoryFilterMelee: /* csgo_schinese.txt */"近战武器",
  InventoryFilterMidTier: /* csgo_schinese.txt */"中级",
  InventoryFilterMisc: /* csgo_schinese.txt */"杂项",
  InventoryFilterMusicKits: /* csgo_schinese.txt */"音乐盒",
  InventoryFilterNewest: /* csgo_schinese.txt */"最新",
  InventoryFilterPatches: /* csgo_schinese.txt */"布章",
  InventoryFilterPistols: /* csgo_schinese.txt */"手枪",
  InventoryFilterQuality: /* csgo_schinese.txt */"品质",
  InventoryFilterRifles: /* csgo_schinese.txt */"步枪",
  InventoryFilterSearch: /* csgo_schinese.txt */"键入搜索",
  InventoryFilterSouvenirCases: /* csgo_schinese.txt */"纪念包",
  InventoryFilterStickerCapsules: /* csgo_schinese.txt */"印花胶囊",
  InventoryFilterStickers: /* csgo_schinese.txt */"印花",
  InventoryFilterTools: /* csgo_schinese.txt */"工具",
  InventoryFilterType: /* csgo_schinese.txt */"类型",
  InventoryFilterWeaponCases: /* csgo_schinese.txt */"武器箱",
  InventoryItemContainsOne: /* csgo_schinese.txt */"包含下列物品之一：",
  InventoryItemDelete: /* csgo_schinese.txt */"删除",
  InventoryItemEdit: /* csgo_schinese.txt */"编辑",
  InventoryItemEquip: /* csgo_schinese.txt */"装备",
  InventoryItemExterior: /* csgo_schinese.txt */"外观：",
  InventoryItemInspect: /* csgo_schinese.txt */"检视",
  InventoryItemInspectFinishCatalog: /* csgo_schinese.txt */"皮肤编号",
  InventoryItemInspectInGame: /* csgo_schinese.txt */"在游戏中检视…",
  InventoryItemInspectPatternTemplate: /* csgo_schinese.txt */"图案模板",
  InventoryItemInspectWearRating: /* csgo_schinese.txt */"磨损率",
  InventoryItemMVPStatTrakCount: /* csgo_schinese.txt */"StatTrak™ 官方竞技 MVP 次数:",
  InventoryItemNew: /* csgo_schinese.txt */"最新！",
  InventoryItemRareItem: /* csgo_schinese.txt */"或一件极其罕见的特殊物品！",
  InventoryItemRarity: /* csgo_schinese.txt */"稀有度：",
  InventoryItemRemovePatch: /* csgo_schinese.txt */"移除布章",
  InventoryItemRename: /* csgo_schinese.txt */"重命名",
  InventoryItemRenameStorageUnit: /* csgo_schinese.txt */"更改标签",
  InventoryItemScrapeSticker: /* csgo_schinese.txt */"刮去印花",
  InventoryItemStatTrak: /* csgo_schinese.txt */"StatTrak™",
  InventoryItemStatTrakCount: /* csgo_schinese.txt */"StatTrak™ 已认证杀敌数:",
  InventoryItemStatTrakDesc: /* csgo_schinese.txt */"该物品具有 StatTrak™ 技术，在其所有者装备时能跟踪若干统计数据。",
  InventoryItemStorageUnitDeposit: /* csgo_schinese.txt */"存放物品",
  InventoryItemStorageUnitEmptyBody: /* csgo_schinese.txt */"库存存储组件允许您存储超过库存容量限制（{1}件）的物品。您选中的库存存储组件为空。在任何时间您都可以从库存将您的物品存入库存存储组件，从库存存储组件取回物品到库存，或者您可以用此组件管理您的收藏品。",
  InventoryItemStorageUnitEmptyClose: /* csgo_schinese.txt */"确定",
  InventoryItemStorageUnitEmptyTitle: /* csgo_schinese.txt */"库存存储组件为空",
  InventoryItemStorageUnitInspect: /* csgo_schinese.txt */"检视",
  InventoryItemStorageUnitRetrieve: /* csgo_schinese.txt */"取回物品",
  InventoryItemSwapStatTrak: /* csgo_schinese.txt */"打开 StatTrak™ 数据互换器",
  InventoryItemTeam: /* csgo_schinese.txt */"队伍：",
  InventoryItemTeamAny: /* csgo_schinese.txt */"任意",
  InventoryItemTeamCT: /* csgo_schinese.txt */"CT",
  InventoryItemTeamT: /* csgo_schinese.txt */"T",
  InventoryItemUnequip: /* csgo_schinese.txt */"解除装备",
  InventoryItemUnlockContainer: /* csgo_schinese.txt */"开箱",
  InventoryItemUseStorageUnit: /* csgo_schinese.txt */"开始使用此组件",
  InventorySelectAnItem: /* csgo_schinese.txt */"选择一个物品与之搭配使用：",
  InventorySelectInspectContents: /* csgo_schinese.txt */"检视内容",
  InventorySelectItemToDeposit: /* csgo_schinese.txt */"选择物品以存入",
  InventorySelectItemToRetrieve: /* csgo_schinese.txt */"选择要取回的物品",
  ItemRarityAncient: /* csgo_schinese.txt */"非凡",
  ItemRarityCommon: /* csgo_schinese.txt */"普通级",
  ItemRarityDefault: /* csgo_schinese.txt */"默认",
  ItemRarityImmortal: /* csgo_schinese.txt */"违禁",
  ItemRarityLegendary: /* csgo_schinese.txt */"奇异",
  ItemRarityMythical: /* csgo_schinese.txt */"卓越",
  ItemRarityNameAgent: /* csgo_schinese.txt */"探员",
  ItemRarityNameCollectible: /* csgo_schinese.txt */"收藏品",
  ItemRarityNameContainer: /* csgo_schinese.txt */"武器箱",
  ItemRarityNameContract: /* csgo_schinese.txt */"合同",
  ItemRarityNameEquipment: /* csgo_schinese.txt */"装备",
  ItemRarityNameGloves: /* csgo_schinese.txt */"手套",
  ItemRarityNameGraffiti: /* csgo_schinese.txt */"涂鸦",
  ItemRarityNameKey: /* csgo_schinese.txt */"钥匙",
  ItemRarityNameKnife: /* csgo_schinese.txt */"匕首",
  ItemRarityNameMachinegun: /* csgo_schinese.txt */"机枪",
  ItemRarityNameMusicKit: /* csgo_schinese.txt */"音乐盒",
  ItemRarityNamePatch: /* csgo_schinese.txt */"布章",
  ItemRarityNamePistol: /* csgo_schinese.txt */"手枪",
  ItemRarityNameRifle: /* csgo_schinese.txt */"步枪",
  ItemRarityNameSMG: /* csgo_schinese.txt */"微型冲锋枪",
  ItemRarityNameShotgun: /* csgo_schinese.txt */"霰弹枪",
  ItemRarityNameSniperRifle: /* csgo_schinese.txt */"狙击步枪",
  ItemRarityNameSticker: /* csgo_schinese.txt */"印花",
  ItemRarityNameTool: /* csgo_schinese.txt */"工具",
  ItemRarityRare: /* csgo_schinese.txt */"高级",
  ItemRarityUncommon: /* csgo_schinese.txt */"中级",
  ItemSwapStatTrakAccept: /* csgo_schinese.txt */"接受",
  ItemSwapStatTrakClose: /* csgo_schinese.txt */"关闭",
  ItemSwapStatTrakDesc: /* csgo_schinese.txt */"该物品可以将两种相同物品类型的 StatTrak™ 数据互换。",
  ItemSwapStatTrakUse: /* csgo_schinese.txt */"StatTrak™ 互换器",
  ItemSwapStatTrakWarn: /* csgo_schinese.txt */"该 StatTrak™ 数据互换器仅能被使用一次",
  ItemWeaponRarityAncient: /* csgo_schinese.txt */"隐秘",
  ItemWeaponRarityCommon: /* csgo_schinese.txt */"消费级",
  ItemWeaponRarityDefault: /* csgo_schinese.txt */"基础",
  ItemWeaponRarityImmortal: /* csgo_schinese.txt */"违禁",
  ItemWeaponRarityLegendary: /* csgo_schinese.txt */"保密",
  ItemWeaponRarityMythical: /* csgo_schinese.txt */"受限",
  ItemWeaponRarityRare: /* csgo_schinese.txt */"军规级",
  ItemWeaponRarityUncommon: /* csgo_schinese.txt */"工业级",
  ItemWearBS: /* csgo_schinese.txt */"战痕累累",
  ItemWearFN: /* csgo_schinese.txt */"崭新出厂",
  ItemWearFT: /* csgo_schinese.txt */"久经沙场",
  ItemWearMW: /* csgo_schinese.txt */"略有磨损",
  ItemWearWW: /* csgo_schinese.txt */"破损不堪",
  RemovePatchRemove: /* csgo_schinese.txt */"移除布章",
  RemovePatchRemoveDesc: /* csgo_schinese.txt */"请确认您是否想要将此布章从您的探员身上移除。移除的布章会被摧毁。",
  RemovePatchUse: /* csgo_schinese.txt */"移除布章",
  RemovePatchWarn: /* csgo_schinese.txt */"从  上移除一个布章",
  RenameCancel: /* csgo_schinese.txt */"取消",
  RenameEnterName: /* csgo_schinese.txt */"为  键入一个新名称",
  RenameRename: /* csgo_schinese.txt */"重命名",
  RenameStorageUnitClose: /* csgo_schinese.txt */"关闭",
  RenameStorageUnitEnterName: /* csgo_schinese.txt */"为  键入一个新名称",
  RenameStorageUnitFirstNameWarn: /* csgo_schinese.txt */"为您的私人库存存储组件键入描述标签，并开始使用此组件以储存物品。",
  RenameStorageUnitNewNameWarn: /* csgo_schinese.txt */"为这个库存存储组件键入一个新的描述标签",
  RenameStorageUnitRename: /* csgo_schinese.txt */"定制",
  RenameStorageUnitUse: /* csgo_schinese.txt */"定制您的库存存储组件",
  RenameUse: /* csgo_schinese.txt */"使用名称标签",
  RenameWarn: /* csgo_schinese.txt */"名称标签只能使用一次",
  ScrapeStickerCancel: /* csgo_schinese.txt */"取消",
  ScrapeStickerClose: /* csgo_schinese.txt */"关闭",
  ScrapeStickerRemove: /* csgo_schinese.txt */"移除印花",
  ScrapeStickerRemoveDesc: /* csgo_schinese.txt */"如果您继续刮除印花，印花将从物品上移除并摧毁。",
  ScrapeStickerUse: /* csgo_schinese.txt */"刮去印花",
  ScrapeStickerWarn: /* csgo_schinese.txt */"从  上刮去一个印花",
  StickerPickerRemove: /* csgo_schinese.txt */"移除",
  APIPageHeader: "API 接口文档",
  CaseAddKeyConfirm: "确认制作钥匙",
  CaseSeed: "图案编号",
  CaseWear: "磨损度",
  CraftBy: "制作者",
  CraftConfirmHeader: "确认制作",
  CraftSearchPlaceholder: "搜索物品...",
  CraftSelectHeader: "正在制作物品...",
  CraftSharedHeader: "分享的制作",
  EditorCraft: "制作",
  EditorNametagPlaceholder: "输入自定义名称...",
  EditorStickerWear: "印花磨损度",
  GridItemNoItemsToDisplay: "没有可显示的物品",
  HeaderAPILabel: "API",
  HeaderCraftCannotCraft: "你无法制作。",
  HeaderCraftInventoryFull: "你的库存已满。",
  HeaderCraftLabel: "制作物品",
  HeaderDonate: "捐赠",
  HeaderInventoryLabel: "自定义库存",
  HeaderSettingsLabel: "设置",
  HeaderSignedInAsLabel: "已登录为",
  HeaderSignInLabel: "登录以同步",
  HeaderSignOutLabel: "登出",
  InventoryItemEquipBothTeams: "装备至双方",
  InventoryItemEquipCT: "装备至 CT 方",
  InventoryItemEquipT: "装备至 T 方",
  InventoryItemInspectCopied: "已复制命令！",
  InventoryItemSeed: "图案编号：",
  InventoryItemShare: "分享",
  InventoryItemShareCopied: "已复制链接！",
  InventoryItemUnequipCT: "解除 CT 方装备",
  InventoryItemUnequipT: "解除 T 方装备",
  InventoryItemWear: "磨损度：",
  InventoryNoItemsToDisplay: "没有可显示的物品",
  JavaScriptRequired: "请启用 JavaScript 并刷新页面。",
  Language$brazilian: "Português do Brasil",
  Language$bulgarian: "Български",
  Language$czech: "Čeština",
  Language$danish: "Dansk",
  Language$dutch: "Nederlands",
  Language$english: "English",
  Language$finnish: "Suomi",
  Language$french: "Français",
  Language$german: "Deutsch",
  Language$greek: "Ελληνικά",
  Language$hungarian: "Magyar",
  Language$indonesian: "Bahasa Indonesia",
  Language$italian: "Italiano",
  Language$japanese: "日本語",
  Language$koreana: "한국어",
  Language$latam: "Español (Latinoamérica)",
  Language$norwegian: "Norsk",
  Language$polish: "Polski",
  Language$portuguese: "Português",
  Language$romanian: "Română",
  Language$russian: "Русский",
  Language$schinese: "简体中文",
  Language$spanish: "Español",
  Language$swedish: "Svenska",
  Language$tchinese: "繁體中文",
  Language$thai: "ไทย",
  Language$turkish: "Türkçe",
  Language$ukrainian: "Українська",
  Language$vietnamese: "Tiếng Việt",
  PatchPickerHeader: "选择布章...",
  PatchPickerSearchPlaceholder: "搜索布章...",
  SettingsBackground: "背景",
  SettingsBackgroundRandom: "随机",
  SettingsConfirmRemoveAllItems: "你确定要移除库存中的所有物品吗？\n此操作无法撤销。",
  SettingsHeader: "设置",
  SettingsHideFilters: "隐藏筛选器",
  SettingsHideFreeItems: "隐藏默认物品",
  SettingsLanguage: "语言",
  SettingsRemoveAllItems: "重置库存",
  SettingsSave: "保存",
  SettingsStatsForNerds: "极客统计",
  StickerPickerFilterPlaceholder: "按类别筛选...",
  StickerPickerHeader: "选择印花...",
  StickerPickerNA: "无",
  StickerPickerSearchPlaceholder: "搜索印花...",
  SyncErrorContinue: "重试",
  SyncErrorDesc: "同步更改时发生错误。",
  SyncErrorTitle: "同步错误",
  SyncWarnText: "你尚未登录，你的更改将不会被同步。"
};
